module.exports = {
    INICIO_SESION: 1,
    CREAR_USUARIO: 2,
    CAMBIO_ROL: 3,
    CREACION_HOJA_VIDA: 4,
    AGENDAMIENTO_MANTENIMIENTO: 5,
    CAMBIO_CONTRASEÑA: 6,
    CAMBIARON_DATOS_USUARIO: 7,
    CREACION_DE_PROVEEDOR: 8,
    ELIMINO_PROVEEDOR: 9,
    CREAR_SWITCH: 10
};
