module.exports = {
    INICIO_SESION: 1,
    CREACION_USUARIO: 2,
    CAMBIO_ROL: 3,
    CREACION_HOJA_VIDA: 4,
    AGENDAMIENTO_MANTENIMIENTO: 5,
    CAMBIO_CONTRASEÑA: 6,
    CAMBIARON_DATOS_USUARIO: 7,
    CREACION_DE_PROVEEDOR: 8,
    ELIMINO_PROVEEDOR: 9,
    CREARACION_SWITCH: 10,
    CANCELACION_MANTENIMIENTO: 11,
    ACTUALIZAR_HOJA_DE_VIDA: 12,
    DESACTIVAR_HOJA_DE_VIDA: 13,
    ACTUALIZAR_EQUIPO: 14,
    ELIMINAR_EQUIPO: 15,
    CREACION_EQUIPO: 16
};
